#!/bin/bash
tmpDir="/tmp/learning-goals"
rm -rf $tmpDir
mkdir $tmpDir
gitRepo=https://github.com/isaqb-org/curriculum-foundation
curDir=$(pwd)
slidesDir=${curDir}/slide-decks

cd $tmpDir
lg_fileName="all-cpsa-f-learning-goals.adoc"
outFile="$tmpDir/$lg_fileName"


cat > $outFile <<EOF
:docinfo: shared

== All CPSA-F learning goals
For reference purposes. +
 +

[.smaller]
© (Copyright), International Software Architecture Qualification Board e. V. (iSAQB® e. V.) 2024

_Source: ${gitRepo}_

_Downloaded on $(date)_

// This file is automatically generated - changes will be overwritten by next update

EOF


git clone $gitRepo

cd $tmpDir/curriculum-foundation/docs
for dir in $(ls -1 | egrep '0.+-')
do
  cd $tmpDir/curriculum-foundation/docs/$dir
  echo "Processing $(pwd)"
  for file in $(ls -1 LG* 2>/dev/null)
  do
    echo "" >> $outFile
    echo "" >> $outFile

    startLine=$(cat $file | grep -n 'tag::EN\[\]' | cut -d ':' -f -1);
    fileLen=$(tail +$startLine $file | wc -l)
    if [ $fileLen -lt 20 ]
    then
      echo "[.learning-goal-printable]" >> $outFile
    elif [ $fileLen -lt 30 ]
    then
      # large number of lines; apply smaller font
      echo "[.learning-goal-printable-smaller]" >> $outFile
    else
      # large number of lines; apply smallest font
      echo "[.learning-goal-printable-smallest]" >> $outFile
    fi
    tail +$startLine $file | grep -v '// tag' | grep -v '// end' | grep -v '\[\[LG-' | sed 's@==== LG@=== LG@g' | sed 's@===== {references}@==== {references}@g' | sed 's@{glossary_url}@@g' |  sed 's@\[[a-z /\-]*] @ @g' >> $outFile
  done
done

cp $outFile $slidesDir
echo "Generated $slidesDir/$lg_fileName"
