#!/bin/bash
tmpDir="/tmp/mock-exam-questions"
rm -rf $tmpDir
mkdir $tmpDir
gitRepo=https://github.com/isaqb-org/examination-foundation
curDir=$(pwd)
topicDir=${curDir}/topics

cd $tmpDir
output_fileName="00.mock-exam-questions.adoc"
outFile="$tmpDir/$output_fileName"

git clone $gitRepo

cd $tmpDir
cd examination-foundation/raw/mock_exam/docs/questions


echo "Includes for all generated files:"

for curFile in $(ls -1 question*)
do

  questionId=$(grep 'ID: ' $curFile | head -n 1 | sed 's@\*\*@@g' | sed 's@ID: @@g')

  startLine=$(grep -n '// tag::EN\[\]' $curFile | cut -d ':' -f -1)
  startLine=$((startLine+1))
  endLine=$(grep -n '// end::EN\[\]' $curFile | cut -d ':' -f -1)
  questionLen=$((endLine-startLine))
  outFileName="QZ.ME.$questionId.adoc"

    if [ $questionLen -lt 35 ]
    then
      styleTag="[.quiz-question-printable]"
    elif [ $questionLen -lt 55 ]
    then
      # large number of lines; apply smaller font
      styleTag="[.quiz-question-printable-smaller]"
    else
      # large number of lines; apply smallest font
      styleTag="[.quiz-question-printable-smallest]"
    fi


cat > $topicDir/$outFileName <<EOF
// © (Copyright), International Software Architecture Qualification Board e. V. (iSAQB® e. V.) 2023
// Source: ${gitRepo}
// This file is automatically generated - changes will be overwritten by next update
EOF

  # Question slide
  echo "[transition=none]" >> $topicDir/$outFileName
  echo "[.align-left]" >> $topicDir/$outFileName
  echo $styleTag >> $topicDir/$outFileName
  tail +$startLine $curFile | head -n $questionLen | grep -v '=== Question' | sed 's@\*\*ID: @=== Question @g' | sed 's@\*\*$@@g' | sed 's@{n}@@g' | sed 's@{y}@@g' >> $topicDir/$outFileName
  echo "[.quiz-question-footnote]" >> $topicDir/$outFileName
  echo "Source: iSAQB® CPSA-F® mock exam"  >> $topicDir/$outFileName

  # Answer slide
  echo "[transition=none]" >> $topicDir/$outFileName
  echo "[.align-left]" >> $topicDir/$outFileName
  echo $styleTag >> $topicDir/$outFileName
  tail +$startLine $curFile | head -n $questionLen | grep -v '=== Question' | sed 's@\*\*ID: @=== Answer @g' | sed 's@\*\*$@@g' | sed 's@{n}@❌@g' | sed 's@{y}@✅@g' >> $topicDir/$outFileName
  echo "[.quiz-question-footnote]" >> $topicDir/$outFileName
  echo "Source: iSAQB® CPSA-F® mock exam"  >> $topicDir/$outFileName

  echo "include::{includedir}/$outFileName[]"

done



